name: build
on:
  push:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: setup ndk
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e
          local-cache: true
      - name: setup haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
      - name: haxe lib
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm
          haxelib run hmm install
          haxelib git hxcpp https://github.com/haxefoundation/hxcpp
          haxelib run lime rebuild hxcpp
      - name: mobile
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_11_X64
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: compile
        run: haxelib run lime build android
      - name: push
        uses: actions/upload-artifact@main
        with:
          name: fnf
          path: export/release/android/bin/app/build/outputs/apk/debug
